name: Build and Push Docker

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      dockerfile_changed: ${{ steps.filter.outputs.dockerfile }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Paths filter
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            dockerfile:
              - 'docker/Dockerfile'

  build-push:
    needs: detect-changes
    if: needs.detect-changes.outputs.dockerfile_changed == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      IMAGE: junspring/2025-autorace-clothoid-a
      TAG: latest
      ROS_DISTRO: noetic
    steps:
      - uses: actions/checkout@v4

      # Docker Hub 로그인 (필수: 저장소 시크릿에 사용자/토큰 추가)
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: junspring
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        run: |
          docker build -t "$IMAGE:$TAG" -t "$IMAGE:latest" ./docker

      - name: Smoke test (catkin_make)
        run: |
          docker run --rm \
            -v "${{ github.workspace }}/src:/catkin_ws/src:ro" \
            "$IMAGE" \
            bash -lc '
              set -e
              source /opt/ros/$ROS_DISTRO/setup.bash
              apt-get update
              mkdir -p /tmp/ws/src
              cp -a /catkin_ws/src/. /tmp/ws/src/
              cd /tmp/ws
              catkin_make -DCMAKE_BUILD_TYPE=Release
            '

      - name: Push images
        run: |
          docker push "$IMAGE:$TAG"
