name: PR Validate with Prebuilt Docker

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

env:
  IMAGE: junspring/2025-autorace-clothoid-a:latest
  ROS_DISTRO: noetic

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      src_changed: ${{ steps.filter.outputs.src }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Paths filter
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            src:
              - 'src'

  build-test:
    needs: detect-changes
    if: needs.detect-changes.outputs.src_changed == 'true'
    runs-on: [self-hosted, linux, docker]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pull prebuilt image
        run: |
          docker pull "$IMAGE"

      - name: catkin_make inside container
        run: |
          docker run --rm \
            -v "${{ github.workspace }}/src:/catkin_ws/src:ro" \
            "$IMAGE" \
            bash -lc '
              set -e
              source /opt/ros/$ROS_DISTRO/setup.bash
              apt-get update
              rosdep update
              mkdir -p /tmp/ws/src
              cp -a /catkin_ws/src/. /tmp/ws/src/
              cd /tmp/ws
              rosdep install --from-paths src --ignore-src -r -y
              catkin_make -DCMAKE_BUILD_TYPE=Release
            '
